[tool.poetry]
name = "libpdf"
version = "0.0.1"
description = "Extract structured data from PDFs."
authors = [
    "Marco Heinemann <marco.heinemann@useblocks.com>",
]
maintainers = [
    "Jui-Wen Chen <jui-wen.chen@useblocks.com>",
    "Haiyang Zhang <haiyang.zhang@useblocks.com>",
]
license = 'MIT'
readme = 'README.rst'
homepage = 'http://pypi.python.org/pypi/libpdf'
repository = 'http://github.com/useblocks/libpdf'
documentation = 'http://libpdf.readthedocs.io/en/latest'
classifiers = [
    'Development Status :: 3 - Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: MIT License',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
    'Topic :: Scientific/Engineering',
    'Topic :: Scientific/Engineering :: Information Analysis',
    'Topic :: Software Development',
    'Topic :: Software Development :: Libraries',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Topic :: Text Processing',
    'Topic :: Utilities',
]

[tool.poetry.dependencies]
python = "^3.6"
chardet = "^3"
click = "^7"
importlib-metadata = { version = "^1.6.0", python = "~3.6 || ~3.7" }
pdfplumber = { git = "https://github.com/useblocks/pdfplumber.git" }
PyYAML = "^5"
"ruamel.yaml" = "^0.16.10"
"pdfminer.six" = {git = "https://github.com/useblocks/pdfminer.six", rev = "develop"}

# optional dependencies
tqdm = { version = "^4.50.0", optional = true }
colorama = { version = "^0.4.4", optional = true }
camelot-py = { version = "^0.7", optional = true }
opencv-python = { version = "^3.4.2.17", optional = true }

[tool.poetry.extras]
tqdm = ["tqdm"]
colorama = ["colorama"]
camelot = ["camelot-py", "opencv-python"]

[tool.poetry.dev-dependencies]
# testing
pytest = "<=5.3.5"  # fixed to this version because of https://github.com/pytest-dev/pytest/issues/6925
pytest-cov = "*"
tox = "*"
pytest-xdist = "*"  # parallelisation

# linters / formatting
flake8 = "*"
flake8-blind-except = "*"       # Checks for blind, catch-all except statements (only py27)
flake8-bugbear = "*"            # Finding likely bugs and design problems in your program
flake8-builtins = "*"           # Check for Python builtins being used as variables or parameters
flake8-commas = "*"             # Flake8 lint for trailing commas
flake8-comprehensions = "*"     # Help you write better list/set/dict comprehensions
flake8-debugger = "*"           # ipdb/pdb statement checker plugin for flake8
flake8-deprecated = "*"         # Warns about deprecated method calls.
flake8-docstrings = "*"         # Uses pydocstyle to check docstrings (PEP 257)
flake8-import-order = "*"       # Checks the ordering of import statements.
flake8-mutable = "*"            # Checks for mutable defaults
flake8-pep3101 = "*"            # Checks for old string formatting.
flake8-quotes = "*"             # Enforce single quotes instead of double quotes
flake8-rst-docstrings = "*"     # Validating Python docstrings markup as reStructuredText (RST)
flake8-string-format = "*"      # Check the strings and parameters using str.format
flake8-tidy-imports = "*"       # Find unnecessary import aliases
flake8-tuple = "*"              # Check code for 1 element tuple
flake8-formatter-abspath = "*"  # Formatter to get absolute file paths for IDE external tool calls

pylint = "*"
black = { version = "^20.0", allow-prereleases = true }
mypy = "^0.790"

# docs
sphinx_rtd_theme = "*"
sphinx = "*"
sphinxcontrib-needs = "*"
sphinxcontrib-plantuml = "*"

[tool.poetry.scripts]
libpdf = 'libpdf.core:main_cli'

[tool.black]
line-length = 120
target-version = ['py38']
skip-string-normalization = 'True'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
