name: Run tox tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry and tox
      run: |
        python -m pip install poetry tox

    - name: Run tox env pytest
      run: |
        tox -e py${{ matrix.python-version }}

  flake8_pylint_docs_black:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install poetry and tox
      run: |
        python -m pip install poetry tox

    - name: Run tox env flake8
      run: |
        tox -e flake8

    - name: Run tox env pylint
      run: |
        tox -e pylint

    - name: Run tox env docs
      run: |
        tox -e docs

    - name: Run tox env black
      run: |
        tox -e black
